services:
  - type: web
    name: research-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python research_server_cloud.py
    envVars:
      - key: PORT
        value: 8001